version: '3'
services:
  web:
    image: nginx:1.21.5
    container_name: oas-web
    depends_on:
      - docker-mysql
      - php
    links:
      - docker-mysql
      - php
    volumes:
      - .:/var/www/html
      - ./.docker/nginx:/etc/nginx/conf.d/
    ports:
      - "80:80"
  php:
    build:
      context: .
      dockerfile: ./.docker/php/dockerfile
    volumes:
      - .:/var/www/html
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
  docker-mysql:
    image: mysql:8.0
    container_name: oas-db
    restart: always
    environment:
        - MYSQL_DATABASE=my_art_site
        - MYSQL_ROOT_PASSWORD=root
    ports:
        - "3306:3306"
    volumes:
        - dbdata:/var/lib/mysql
volumes:
  dbdata: